language: node_js
node_js:
 - "stable"
cache:
 directories:
 - node_modules
script:
 - CI=false
 - npm run build
 - npm add surge
 - npm test
deploy:
  provider: surge
  project: ./build/
  domain: schej-frontend.surge.sh
  skip_cleanup: true
